import { DowntimeReport, ReasonCategory } from './types';

export const PRODUCTION_LINES = [
  'Dây chuyền LR RO',
  'Dây chuyền Bếp Gas',
];

export const REPORTERS = [
  'Nguyễn Minh Hoàng Khiêm',
  'Nguyễn Quốc Thịnh',
];

export interface Product {
  name: string;
  line: 'Dây chuyền LR RO' | 'Dây chuyền Bếp Gas';
  unitPrice: number; // VNĐ
  standardRate: number; // sản phẩm/giờ (SP/H)
}

export const PRODUCTS: Product[] = [
  { name: 'Máy lọc nước RO Sunhouse 9 lõi SHA8858K', line: 'Dây chuyền LR RO', unitPrice: 4500000, standardRate: 60 },
  { name: 'Máy lọc nước RO Sunhouse 10 lõi SHA88116K', line: 'Dây chuyền LR RO', unitPrice: 5200000, standardRate: 48 },
  { name: 'Máy lọc nước RO Nóng Lạnh SHA76213CK', line: 'Dây chuyền LR RO', unitPrice: 7500000, standardRate: 36 },
  { name: 'Bếp gas đôi Sunhouse SHB3365', line: 'Dây chuyền Bếp Gas', unitPrice: 1200000, standardRate: 120 },
  { name: 'Bếp gas dương kính Sunhouse SHB201MT', line: 'Dây chuyền Bếp Gas', unitPrice: 1500000, standardRate: 90 },
  { name: 'Bếp gas âm cao cấp SHB5536', line: 'Dây chuyền Bếp Gas', unitPrice: 2800000, standardRate: 60 },
];

export const REASON_CATEGORIES: ReasonCategory[] = [
  'Sự cố máy móc/thiết bị',
  'Thiếu nguyên vật liệu',
  'Thay đổi mã hàng/Gá đặt',
  'Chờ kiểm tra chất lượng',
  'Sự cố vận hành/Nhân sự',
  'Sự cố điện/nước/khí nén',
  'Lý do khác',
];

export const REASON_COLORS: Record<ReasonCategory, string> = {
  'Sự cố máy móc/thiết bị': '#EF4444', // Red
  'Thiếu nguyên vật liệu': '#F59E0B', // Amber
  'Thay đổi mã hàng/Gá đặt': '#3B82F6', // Blue
  'Chờ kiểm tra chất lượng': '#8B5CF6', // Purple
  'Sự cố vận hành/Nhân sự': '#EC4899', // Pink
  'Sự cố điện/nước/khí nén': '#10B981', // Green
  'Lý do khác': '#6B7280', // Gray
};

export const INITIAL_DOWNTIME_REPORTS: DowntimeReport[] = [
  {
    id: 'dt-1',
    date: '2026-06-21',
    shift: 'Ca 1',
    line: 'Dây chuyền LR RO',
    equipment: 'Máy lọc màng RO #1',
    startTime: '08:15',
    endTime: '09:30',
    duration: 75,
    reasonCategory: 'Sự cố máy móc/thiết bị',
    details: 'Rò rỉ khớp nối áp lực cao tại cụm bơm màng chính.',
    solution: 'Thay thế gioăng cao su chịu áp lực, quấn băng tan gia cố và xiết chặt lực đai ốc.',
    pic: 'Nguyễn Minh Hoàng Khiêm',
    status: 'Đã khắc phục',
    createdAt: '2026-06-21T09:35:00.000Z',
    productName: 'Máy lọc nước RO Sunhouse 9 lõi SHA8858K',
    productUnitPrice: 4500000,
    standardRate: 60,
  },
  {
    id: 'dt-2',
    date: '2026-06-21',
    shift: 'Ca 2',
    line: 'Dây chuyền Bếp Gas',
    equipment: 'Hệ thống đánh lửa tự động',
    startTime: '14:20',
    endTime: '14:50',
    duration: 30,
    reasonCategory: 'Thay đổi mã hàng/Gá đặt',
    details: 'Thay đổi gá đặt khuôn gá cụm hoa sen chia lửa cho mã bếp SHD-2026.',
    solution: 'Điều chỉnh lại khoảng cách đầu đánh lửa cơ và gá kẹp giữ thân bếp.',
    pic: 'Nguyễn Quốc Thịnh',
    status: 'Đã khắc phục',
    createdAt: '2026-06-21T14:55:00.000Z',
    productName: 'Bếp gas đôi Sunhouse SHB3365',
    productUnitPrice: 1200000,
    standardRate: 120,
  },
  {
    id: 'dt-3',
    date: '2026-06-22',
    shift: 'Ca 1',
    line: 'Dây chuyền LR RO',
    equipment: 'Trạm cấp vỏ tủ RO tự động',
    startTime: '10:00',
    endTime: '11:45',
    duration: 105,
    reasonCategory: 'Thiếu nguyên vật liệu',
    details: 'Chậm cung ứng vỏ tủ sơn tĩnh điện từ phân xưởng đột dập cơ khí chuyển sang.',
    solution: 'Huy động thủ công bằng xe đẩy nâng chuyển khẩn cấp vỏ tủ từ bãi đệm.',
    pic: 'Nguyễn Minh Hoàng Khiêm',
    status: 'Đã khắc phục',
    createdAt: '2026-06-22T11:50:00.000Z',
    productName: 'Máy lọc nước RO Sunhouse 10 lõi SHA88116K',
    productUnitPrice: 5200000,
    standardRate: 48,
  },
  {
    id: 'dt-4',
    date: '2026-06-22',
    shift: 'Ca 3',
    line: 'Dây chuyền Bếp Gas',
    equipment: 'Buồng test rò rỉ khí gas khí nén',
    startTime: '22:15',
    endTime: '23:45',
    duration: 90,
    reasonCategory: 'Sự cố điện/nước/khí nén',
    details: 'Sụt áp áp suất khí nén cấp cho cảm biến đo áp thử rò rỉ van gas.',
    solution: 'Kiểm tra đường ống dẫn khí nén, phát hiện rò rỉ khớp nối nhanh và thay mới.',
    pic: 'Nguyễn Quốc Thịnh',
    status: 'Đã khắc phục',
    createdAt: '2026-06-22T23:50:00.000Z',
    productName: 'Bếp gas dương kính Sunhouse SHB201MT',
    productUnitPrice: 1500000,
    standardRate: 90,
  },
  {
    id: 'dt-5',
    date: '2026-06-23',
    shift: 'Ca 2',
    line: 'Dây chuyền LR RO',
    equipment: 'Trạm kiểm tra rò rỉ nước (Wet test)',
    startTime: '15:30',
    endTime: '16:05',
    duration: 35,
    reasonCategory: 'Chờ kiểm tra chất lượng',
    details: 'Phát hiện rò rỉ khớp nối nhanh lõi số 3 trên loạt 5 máy liên tục. Chờ QA xác nhận nguyên nhân.',
    solution: 'QA lập biên bản, loại bỏ lô cút nối lỗi khuôn nhựa và thay thế linh kiện dự phòng đạt chuẩn.',
    pic: 'Nguyễn Minh Hoàng Khiêm',
    status: 'Đã khắc phục',
    createdAt: '2026-06-23T16:10:00.000Z',
    productName: 'Máy lọc nước RO Nóng Lạnh SHA76213CK',
    productUnitPrice: 7500000,
    standardRate: 36,
  },
  {
    id: 'dt-6',
    date: '2026-06-24',
    shift: 'Ca 1',
    line: 'Dây chuyền Bếp Gas',
    equipment: 'Máy ép lực núm xoay bếp gas',
    startTime: '07:30',
    endTime: '09:50',
    duration: 140,
    reasonCategory: 'Sự cố máy móc/thiết bị',
    details: 'Hỏng van điện từ điều khiển xy-lanh ép trục xoay gây kẹt hành trình ép xuống.',
    solution: 'Thay thế cuộn coi điện từ và xy-lanh dẫn hướng khí nén mới.',
    pic: 'Nguyễn Minh Hoàng Khiêm',
    status: 'Đã khắc phục',
    createdAt: '2026-06-24T09:55:00.000Z',
    productName: 'Bếp gas âm cao cấp SHB5536',
    productUnitPrice: 2800000,
    standardRate: 60,
  },
  {
    id: 'dt-7',
    date: '2026-06-24',
    shift: 'Ca 3',
    line: 'Dây chuyền LR RO',
    equipment: 'Súng vặn vít khí nén tự động',
    startTime: '01:00',
    endTime: '01:45',
    duration: 45,
    reasonCategory: 'Sự cố vận hành/Nhân sự',
    details: 'Công nhân mới thao tác tỳ lực quá mạnh gây mẻ đầu vít vặn màng vỏ cốc RO.',
    solution: 'Thay thế mũi vít, huấn luyện lại lực tỳ và bổ sung gá định vị vít treo.',
    pic: 'Nguyễn Minh Hoàng Khiêm',
    status: 'Đã khắc phục',
    createdAt: '2026-06-24T01:50:00.000Z',
    productName: 'Máy lọc nước RO Sunhouse 9 lõi SHA8858K',
    productUnitPrice: 4500000,
    standardRate: 60,
  },
  {
    id: 'dt-8',
    date: '2026-06-25',
    shift: 'Ca 2',
    line: 'Dây chuyền Bếp Gas',
    equipment: 'Băng tải phân cấp cụm đánh lửa',
    startTime: '16:40',
    endTime: '17:10',
    duration: 30,
    reasonCategory: 'Thiếu nguyên vật liệu',
    details: 'Hết cụm chế hòa khí đánh lửa cơ Magneto tại khay chờ cấp liệu.',
    solution: 'Hối thúc kho trung chuyển giao bổ sung 5 thùng linh kiện Magneto dự phòng.',
    pic: 'Nguyễn Minh Hoàng Khiêm',
    status: 'Đã khắc phục',
    createdAt: '2026-06-25T17:15:00.000Z',
    productName: 'Bếp gas đôi Sunhouse SHB3365',
    productUnitPrice: 1200000,
    standardRate: 120,
  },
  {
    id: 'dt-9',
    date: '2026-06-26',
    shift: 'Ca 1',
    line: 'Dây chuyền Bếp Gas',
    equipment: 'Trạm dán tem nhãn mặt kính',
    startTime: '08:45',
    endTime: '09:25',
    duration: 40,
    reasonCategory: 'Sự cố máy móc/thiết bị',
    details: 'Lệch mắt đọc hồng ngoại cảm biến nhận diện kính của máy dán nhãn tự động.',
    solution: 'Vệ sinh bụi bẩn bám trên thấu kính hồng ngoại, căn chỉnh lại góc nghiêng 15 độ.',
    pic: 'Nguyễn Quốc Thịnh',
    status: 'Đã khắc phục',
    createdAt: '2026-06-26T09:30:00.000Z',
    productName: 'Bếp gas dương kính Sunhouse SHB201MT',
    productUnitPrice: 1500000,
    standardRate: 90,
  },
  {
    id: 'dt-10',
    date: '2026-06-26',
    shift: 'Ca 2',
    line: 'Dây chuyền LR RO',
    equipment: 'Băng tải đóng thùng thành phẩm',
    startTime: '13:10',
    endTime: '13:50',
    duration: 40,
    reasonCategory: 'Lý do khác',
    details: 'Dừng chạy chuyền chính để thực hiện kiểm tra an toàn điện định kỳ phân xưởng Lắp ráp RO.',
    solution: 'Ngắt điện an toàn, đo điện trở nối đất và đóng điện tái sản xuất.',
    pic: 'Nguyễn Minh Hoàng Khiêm',
    status: 'Đã khắc phục',
    createdAt: '2026-06-26T13:55:00.000Z',
    productName: 'Máy lọc nước RO Sunhouse 10 lõi SHA88116K',
    productUnitPrice: 5200000,
    standardRate: 48,
  },
  {
    id: 'dt-11',
    date: '2026-06-26',
    shift: 'Ca 2',
    line: 'Dây chuyền LR RO',
    equipment: 'Máy ép đai thùng tự động',
    startTime: '15:15',
    endTime: '',
    duration: 0,
    reasonCategory: 'Sự cố máy móc/thiết bị',
    details: 'Kẹt dây đai nhựa PP tại cụm dao nhiệt hàn cắt dây đai của máy.',
    solution: 'Đang vệ sinh cặn nhựa bám dính ở lưỡi dao nhiệt và thay thế thanh cuộn đai mới.',
    pic: 'Nguyễn Quốc Thịnh',
    status: 'Đang xử lý',
    createdAt: '2026-06-26T15:20:00.000Z',
    productName: 'Máy lọc nước RO Nóng Lạnh SHA76213CK',
    productUnitPrice: 7500000,
    standardRate: 36,
  }
];
